container:
  image: python

lint_task:
  setup_script:
    - pip install flake8
    - pip install codespell
  script:
    - PYTHONWARNINGS="ignore" flake8 --ignore=E501,F841,W503 --exclude=coldstakepool/contrib,.eggs
    - codespell --check-filenames --disable-colors --quiet-level=7 --ignore-words=tests/lint/spelling.ignore-words.txt -S .git,.eggs,gitianpubkeys,*.pyc,*mnemonics.py,coldstakepool/contrib

test_task:
  script:
    - python setup.py test
